# Generated by Django 4.2.1 on 2023-05-24 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LittleLemonAPI", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="unit_price",
        ),
    ]
